---
RecipeFormatVersion: '2020-01-25'
ComponentName: com.example.IoTCoreMessage
ComponentVersion: 3.2.0
ComponentDescription: A component that sends and receives MQTT messages.
ComponentPublisher: Amazon
ComponentConfiguration:
  DefaultConfiguration:
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        com.example.IoTCoreMessage:mqttproxy:1:
          policyDescription: Allows access to publish and subscribe to all topics.
          operations:
            - aws.greengrass#PublishToIoTCore
            - aws.greengrass#SubscribeToIoTCore
          resources:
            - "*"
ComponentDependencies:
  aws.greengrass.TokenExchangeService:
    VersionRequirement: ">=2.0.0 <3.0.0"
    DependencyType: "HARD"
Manifests:
  - Lifecycle:
      Install: pip3 install awsiotsdk boto3
      Run: |
        python3 -u {artifacts:path}/main.py
    Artifacts:
      - URI: s3://greengrass-component-artifacts-us-east-2/artifacts/com.example.IoTCoreMessage/3.0.0/main.py
        Permission:
          Execute: OWNER